### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by anomalchik** [freemarkw/android_device_asus_X00T#1]
**Alpha 1** 
- [x]  binderized lights hal
- [x]  perf
- [x]  rewrite init
- [x]  cleanup device tree

**Alpha 2** 
- [x]  fix bokeh mode in Snap
- [x]  fix missing interfaces
- [x]  Update to LA.UM.7.2.r1-06700-sdm660.0

**Beta 1** 
- [x]  Audio
- [x]  OMX
- [x]  Media profiles
- [x]  Audio HD (DVC)
- [x]  Wireless Display
- [x]  VoLTE VoWIFI
- [x]  Update blobs to pie unreleased stable

**Beta 2**
- [x] Adaptive Backlight
- [x] Blobls from 053
- [x] lineagehw
- [x] Update to LA.UM.7.2.r1-07200-sdm660.0
- [x] Widevine L1
- [x] sepolicy

**RC**
- [x] try use stock offline charger
- [x] more cleanup
